services:
- docker

addons:
  apt:
    packages:
    - docker-ce
    - python-pip

install: true
before_install:
- sudo apt-get install -y --no-install-recommends docker python-pip jq
- sudo pip install docker-compose httpie

script:
- docker-compose up -V --build --remove-orphans --force-recreate &
- while [[ $(docker ps -n 2 -qf health=healthy | wc -l) -lt 2 ]] ; do echo -ne '.' ; done
- http :80
- for c in $(docker ps -aq) ; do docker rm -f -v $c ; done;
- for i in $(docker images -aq) ; do docker rmi -f $i ; done;
- docker-compose down -v

cache:
  directories:
  - ~/.docker
